sharding:
  jdbc:
    datasource:
      names: dsmaster,dsslave0
      dsmaster:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.26:3306/newsthree?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: newscc
        password: 123qwe

      dsslave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.26:3306/newsfour?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: newsdd
        password: 123qwe

    config:
      masterslave:
        name:
          ds_ms
        master-data-source-name:
          dsmaster
        slave-data-source-names:
          dsslave0
        load-balance-algorithm-type: round_robin





